[tool.black]
line-length = 200


[tool.ruff]
line-length = 200

[tool.ruff.lint]
ignore = [
    "F401",
    "F403",
    "F405",
]

select = [
    "E",
    "F",
    "I",
    "W",
]


[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F403"]
"initialise.py" = ["E501"]
"tests/test_functions.py" = ["W291"]
"src/functions.py" = ["E501"]

"templates/*" = [
    "E402",
    "F821"
]

[tool.ruff.lint.isort]
combine-as-imports = true
force-sort-within-sections = true
section-order = [
  "future",
  "standard-library",
  "first-party",
  "third-party",
  "local-folder",
]
